name: titanic-mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - setuptools
  - pip
  - pip:
      - mlflow==2.13.0
      - scikit-learn==1.4.2
      - pandas==2.2.2
      - numpy==1.26.4
      - joblib==1.4.2
